version: '3.8'

services:
  strapi:
    image: strapi/strapi
    container_name: strapi_mongodb
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_HOST: mongo
      DATABASE_NAME: ${DATABASE_NAME:-strapidb}
      DATABASE_PORT: ${DATABASE_PORT:-27017}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-strapidb_user}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-P@ssw0rd}
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-strapidb}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-strapidb_user}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-P@ssw0rd}
    volumes:
      - ./data:/data/db
